### ISSUE TITLE
Stop based on Date not inclusive of last date.

### ISSUE THREAD

**Issue by echozone** [backdrop-contrib/repeating_dates#17]
Stop based on Date stops up to, not including date entered. Need to enter a (weekly) date a week ahead to include intended last date.

Stop based on Date. Here, 5/24 entered as Stop on. Need to enter 5/31 to display 5/24 as last date:

![stop by date](https://user-images.githubusercontent.com/2477719/166323108-ffdb35fc-a0f2-4fc9-a94a-936b452c755d.png)

Stop based on count correctly includes last date:

![stop by count](https://user-images.githubusercontent.com/2477719/166323197-3fb3dfd1-5778-4572-9530-e9a0bbd0276e.png)

**Comment by indigoxela** [comment]
You should report any issues you experience with rrule parsing upstream: https://github.com/rlanvin/php-rrule/issues That's the library this module uses to parse rules.

"Stop on" actually means "stop before".

**Comment by indigoxela** [comment]
Reopening, as there might be something to improve in the module.

**Comment by indigoxela** [comment]
Confirmed it's a bug, and it should be fixed in #18

**Comment by echozone** [comment]
I'll assume this is what you meant to do. It corrects the stop by date in the rrule, but still does not include it in the view.

![stopbydate2](https://user-images.githubusercontent.com/2477719/166594305-af09a2eb-de1e-4004-a46f-52b57087cef5.png)

**Comment by indigoxela** [comment]
> ... but still does not include it in the view.

The view? Do you mean the display or a views view?

It works for me:

![node-display](https://user-images.githubusercontent.com/842066/166631906-d6f78490-073b-4bb8-ae4c-cd73f1f5fa3e.png)

How did you apply the patch?

**Comment by echozone** [comment]
Yes, I meant not included in the content type display.
Sorry, I just don't understand how we are getting different results. I still get the same result, the last date is not displayed.

I patched it manually since it is so simple. I use the excellent BBEdit, plain text. I compared my .module file with yours online, identical. I cleared site caches directly from the database, ran update.php, cleared browser caches, tested 2 browsers, created a fresh node of the test content type, different dates.

I hope someone else will test.

**Comment by indigoxela** [comment]
@echozone many thanks for clarifying.

That's really odd... Please note that existing field values aren't supposed to change automatically. But as soon as you re-save a node or create a new one, the change should work. You wrote that you also created at least one fresh node, though - and it still didn't work for you.

Did you use the same dates (input values)? If not, which values did you set on that fresh node (start, repeat, end)?

Another thought: what's your timezone?

**Comment by indigoxela** [comment]
Looking closer at it, I belief, it's a timezone handling issue. The pull request has been updated accordingly (still a small change): https://github.com/backdrop-contrib/repeating_dates/pull/18/files

**Comment by echozone** [comment]
You nailed it! Now it works, I'm in US Pacific time, halfway across the planet from you :-)

Do we do RTBC here (Reviewed & tested by the community)?

**Comment by indigoxela** [comment]
The latest release contains the fix. Many thanks for reporting and testing. :+1:
